import type { AppProps } from "next/app";
import Layout from "../components/layout";
import Head from "next/head";
import { Ubuntu } from "next/font/google";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
});

export default function App({ Component, pageProps }: AppProps) {
  const theme = createTheme({
    typography: {
      fontFamily: `${ubuntu.style.fontFamily}, Arial`,
    },
    palette: {
      primary: {
        main: "#333",
      },
      secondary: {
        main: "#eee",
      },
    },
  });

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>

        <meta property="og:title" content="Tech in Trinidad" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.TechInTrinidad.com" />
        <meta
          property="og:image"
          content="https://www.techintrinidad.com/tech_in_tt_logo.png"
        />

        <title>Tech in Trinidad</title>
      </Head>
      <ThemeProvider theme={theme}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </>
  );
}
